### ISSUE TITLE
[PE-D][Tester B] Weird module inputs produce valid search results

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T14-2/tp#125]
inputs that are not of the format of a module code will return valid search results, which probably should not be the intended behaviour of the find command.

for example,

find m/ CS2040S is a valid command

but 

find m/ 4 is also a valid command, although a user would expect that 4 is not a valid module code

this is probably due to the fact that there is no check for module input! (refer to issue 6)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: minjiunn/ped#5

**Comment by parnikkapore** [comment]
Merging into https://github.com/AY2223S1-CS2103T-T14-2/tp/issues/126
