### ISSUE TITLE
[PE-D][Tester E] Chinese character set not recognised as 'm/' argument for add command 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T14-2/tp#133]
Input:

`add aw m/你好 by/3`

Expected output:

added a new 'aw' task with module code 你好 and deadline 3pm

Actual output:

![image.png](https://raw.githubusercontent.com/yeehaoo/ped/main/files/10504584-0658-4084-bc32-b645efb04ac9.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: yeehaoo/ped#4

**Comment by parnikkapore** [comment]
We forgot to update the usage text. We will clarify that module codes are alphanumeric in v1.4 .
